// Storm King's Thunder / Giants on the Frontier — campaign STRUCTURE only.
//
// Concise, paraphrased, factual scaffolds: chapter order, level ranges, entry/
// exit conditions, location/NPC/monster name references, quest & knowledge flag
// ids, transitions, and a small region-travel graph. NO copyrighted prose, no
// read-aloud text. Chapter 1 maps to the authored module; Chapters 2–12 are
// honest scaffolds (playableStatus: 'scaffold') pending authoring.
//
// Source: Storm King's Thunder reference — table of contents and chapter
// summaries (facts only).

import type { CampaignDefinition } from './types';

export const SKT_CAMPAIGN: CampaignDefinition = {
  id: 'skt',
  title: 'Storm King\'s Thunder — Giants on the Frontier',
  premise:
    'Annam the All-Father has shattered the ordning (the giants\' social order); giant kind erupts across the North while King Hekaton is missing. The party rises from local heroes to power-brokers who decide the fate of the Savage Frontier.',
  startChapterId: 'skt-ch1-nightstone',
  regions: ['Savage Frontier', 'Sword Coast', 'Spine of the World', 'Sea of Moving Ice'],

  chapters: [
    {
      id: 'skt-ch1-nightstone',
      title: 'Chapter 1 — A Great Upheaval (Nightstone)',
      levelRange: [1, 3],
      playableStatus: 'authored',
      moduleId: 'skt-nightstone-chapter1',
      entryConditions: ['New party arrives at the recently-attacked village of Nightstone'],
      exitConditions: ['Nightstone investigated and the goblin/ogre threat resolved; a lead points onward'],
      majorLocations: ['Nightstone village', 'drawbridge', 'temple', 'Nightstone Inn', 'Nandar Keep', 'dripping caves', 'tower of Zephyros'],
      majorNpcs: ['Morak Ur\'gray (innkeeper)', 'Kella Darkhope (Zhentarim spy)', 'Zephyros (cloud giant wizard)'],
      majorMonsters: ['goblins', 'ogre', 'goblin boss'],
      questFlags: ['q-nightstone-cleared'],
      knowledgeFacts: ['k-ordning-shattered', 'k-nightstone-attacked'],
    },
    {
      id: 'skt-ch2-rumblings',
      title: 'Chapter 2 — Rumblings',
      levelRange: [1, 5],
      playableStatus: 'scaffold',
      entryConditions: ['Party travels to a Savage Frontier town and helps defend it'],
      exitConditions: ['A town defended and the party recognised; Harshnag\'s trail or the Eye is hinted'],
      majorLocations: ['Triboar', 'Goldenfields', 'Bryn Shander'],
      majorNpcs: ['Darathra Shendrel (Triboar)', 'Abbot Ellardin Darovik (Goldenfields)', 'Duvessa Shane (Bryn Shander)'],
      majorMonsters: ['fire giants', 'frost giants', 'orc raiders'],
      questFlags: ['q-town-defended'],
      knowledgeFacts: ['k-giants-attacking-towns'],
    },
    {
      id: 'skt-ch3-savage-frontier',
      title: 'Chapter 3 — The Savage Frontier',
      levelRange: [5, 5],
      playableStatus: 'scaffold',
      entryConditions: ['Party travels the North pursuing leads about the giant threat'],
      exitConditions: ['Party meets Harshnag and is guided toward the Eye of the All-Father'],
      majorLocations: ['Kryptgarden Forest', 'Grandfather Tree', 'open roads of the North'],
      majorNpcs: ['Harshnag (frost giant ally)'],
      majorMonsters: ['dragons', 'giants', 'wilderness threats'],
      questFlags: ['q-met-harshnag'],
      knowledgeFacts: ['k-harshnag-ally'],
    },
    {
      id: 'skt-ch4-chosen-path',
      title: 'Chapter 4 — The Chosen Path (Eye of the All-Father)',
      levelRange: [5, 5],
      playableStatus: 'scaffold',
      entryConditions: ['Party reaches the Eye of the All-Father temple with Harshnag'],
      exitConditions: ['Party consults the oracle and chooses which giant lord to pursue'],
      majorLocations: ['Eye of the All-Father'],
      majorNpcs: ['the oracle (vision of Annam)', 'Harshnag'],
      majorMonsters: ['Iymrith (disguised / attacks the temple)'],
      questFlags: ['q-consulted-oracle', 'q-chosen-giant-lord'],
      knowledgeFacts: ['k-conch-artifacts', 'k-iymrith-true-role'],
    },
    {
      id: 'skt-ch5-grudd-haug',
      title: 'Chapter 5 — Den of the Hill Giants (Grudd Haug)',
      levelRange: [5, 10],
      playableStatus: 'scaffold',
      entryConditions: ['Party pursues the hill giant lord Chief Guh'],
      exitConditions: ['Chief Guh dealt with; a conch of teleportation recovered'],
      majorLocations: ['Grudd Haug'],
      majorNpcs: ['Chief Guh'],
      majorMonsters: ['hill giants', 'ogres', 'goblins'],
      questFlags: ['q-conch-recovered'],
      knowledgeFacts: ['k-conch-artifacts'],
    },
    {
      id: 'skt-ch6-deadstone-cleft',
      title: 'Chapter 6 — Canyon of the Stone Giants (Deadstone Cleft)',
      levelRange: [5, 10],
      playableStatus: 'scaffold',
      entryConditions: ['Party pursues the stone giant thane Kayalithica'],
      exitConditions: ['Stone giant threat resolved; a conch of teleportation recovered'],
      majorLocations: ['Deadstone Cleft'],
      majorNpcs: ['Thane Kayalithica'],
      majorMonsters: ['stone giants'],
      questFlags: ['q-conch-recovered'],
      knowledgeFacts: ['k-conch-artifacts'],
    },
    {
      id: 'skt-ch7-svardborg',
      title: 'Chapter 7 — Berg of the Frost Giants (Svardborg)',
      levelRange: [5, 10],
      playableStatus: 'scaffold',
      entryConditions: ['Party pursues the frost giant jarl Storvald'],
      exitConditions: ['Frost giant threat resolved; a conch of teleportation recovered'],
      majorLocations: ['Svardborg', 'Sea of Moving Ice'],
      majorNpcs: ['Jarl Storvald'],
      majorMonsters: ['frost giants', 'Isendraug (white dragon)'],
      questFlags: ['q-conch-recovered'],
      knowledgeFacts: ['k-conch-artifacts'],
    },
    {
      id: 'skt-ch8-ironslag',
      title: 'Chapter 8 — Forge of the Fire Giants (Ironslag)',
      levelRange: [5, 10],
      playableStatus: 'scaffold',
      entryConditions: ['Party pursues the fire giant duke Zalto and his colossus plan'],
      exitConditions: ['Fire giant threat resolved; a conch of teleportation recovered'],
      majorLocations: ['Ironslag'],
      majorNpcs: ['Duke Zalto'],
      majorMonsters: ['fire giants'],
      questFlags: ['q-conch-recovered'],
      knowledgeFacts: ['k-conch-artifacts'],
    },
    {
      id: 'skt-ch9-lyn-armaal',
      title: 'Chapter 9 — Castle of the Cloud Giants (Lyn Armaal)',
      levelRange: [5, 10],
      playableStatus: 'scaffold',
      entryConditions: ['Party pursues the cloud giant countess Sansuri'],
      exitConditions: ['Cloud giant threat resolved; a conch of teleportation recovered'],
      majorLocations: ['Lyn Armaal (flying castle)'],
      majorNpcs: ['Countess Sansuri'],
      majorMonsters: ['cloud giants'],
      questFlags: ['q-conch-recovered'],
      knowledgeFacts: ['k-conch-artifacts'],
    },
    {
      id: 'skt-ch10-maelstrom',
      title: 'Chapter 10 — Hold of the Storm Giants (Maelstrom)',
      levelRange: [10, 11],
      playableStatus: 'scaffold',
      entryConditions: ['Party uses a conch to reach the storm giant court of Maelstrom'],
      exitConditions: ['Party allies with Serissa and learns the truth behind Hekaton\'s disappearance'],
      majorLocations: ['Maelstrom'],
      majorNpcs: ['Princess Serissa', 'Mirran', 'Nym'],
      majorMonsters: ['intrigue / assassins'],
      questFlags: ['q-allied-with-serissa'],
      knowledgeFacts: ['k-hekaton-fate', 'k-serissa-role', 'k-kraken-society'],
    },
    {
      id: 'skt-ch11-tentacles',
      title: 'Chapter 11 — Caught in the Tentacles',
      levelRange: [11, 11],
      playableStatus: 'scaffold',
      entryConditions: ['Party tracks the Kraken Society to rescue King Hekaton'],
      exitConditions: ['King Hekaton freed from the Kraken Society'],
      majorLocations: ['Purple Rocks', 'Morkoth (Kraken Society stronghold)'],
      majorNpcs: ['King Hekaton', 'Slarkrethel (Kraken Society)'],
      majorMonsters: ['krakens', 'sahuagin', 'Kraken Society agents'],
      questFlags: ['q-hekaton-freed'],
      knowledgeFacts: ['k-hekaton-fate', 'k-kraken-society'],
    },
    {
      id: 'skt-ch12-doom-of-the-desert',
      title: 'Chapter 12 — Doom of the Desert (Finding Iymrith)',
      levelRange: [11, 12],
      playableStatus: 'scaffold',
      entryConditions: ['The true enemy revealed; party confronts the ancient blue dragon Iymrith'],
      exitConditions: ['Iymrith defeated; the storm giant throne and the ordning addressed'],
      majorLocations: ['Anauroch desert', 'Iymrith\'s lair'],
      majorNpcs: ['King Hekaton', 'Princess Serissa'],
      majorMonsters: ['Iymrith (ancient blue dragon)', 'desert guardians'],
      questFlags: ['q-iymrith-defeated'],
      knowledgeFacts: ['k-iymrith-true-role'],
    },
  ],

  transitions: [
    { fromChapterId: 'skt-ch1-nightstone', toChapterId: 'skt-ch2-rumblings', requires: 'q-nightstone-cleared' },
    { fromChapterId: 'skt-ch2-rumblings', toChapterId: 'skt-ch3-savage-frontier', requires: 'q-town-defended' },
    { fromChapterId: 'skt-ch3-savage-frontier', toChapterId: 'skt-ch4-chosen-path', requires: 'q-met-harshnag' },
    { fromChapterId: 'skt-ch4-chosen-path', toChapterId: 'skt-ch5-grudd-haug', requires: 'q-chosen-giant-lord' },
    { fromChapterId: 'skt-ch4-chosen-path', toChapterId: 'skt-ch6-deadstone-cleft', requires: 'q-chosen-giant-lord' },
    { fromChapterId: 'skt-ch4-chosen-path', toChapterId: 'skt-ch7-svardborg', requires: 'q-chosen-giant-lord' },
    { fromChapterId: 'skt-ch4-chosen-path', toChapterId: 'skt-ch8-ironslag', requires: 'q-chosen-giant-lord' },
    { fromChapterId: 'skt-ch4-chosen-path', toChapterId: 'skt-ch9-lyn-armaal', requires: 'q-chosen-giant-lord' },
    { fromChapterId: 'skt-ch5-grudd-haug', toChapterId: 'skt-ch10-maelstrom', requires: 'q-conch-recovered' },
    { fromChapterId: 'skt-ch6-deadstone-cleft', toChapterId: 'skt-ch10-maelstrom', requires: 'q-conch-recovered' },
    { fromChapterId: 'skt-ch7-svardborg', toChapterId: 'skt-ch10-maelstrom', requires: 'q-conch-recovered' },
    { fromChapterId: 'skt-ch8-ironslag', toChapterId: 'skt-ch10-maelstrom', requires: 'q-conch-recovered' },
    { fromChapterId: 'skt-ch9-lyn-armaal', toChapterId: 'skt-ch10-maelstrom', requires: 'q-conch-recovered' },
    { fromChapterId: 'skt-ch10-maelstrom', toChapterId: 'skt-ch11-tentacles', requires: 'q-allied-with-serissa' },
    { fromChapterId: 'skt-ch11-tentacles', toChapterId: 'skt-ch12-doom-of-the-desert', requires: 'q-hekaton-freed' },
  ],

  milestones: [
    { id: 'm-ch1', chapterId: 'skt-ch1-nightstone', grantsLevel: 3 },
    { id: 'm-ch2', chapterId: 'skt-ch2-rumblings', grantsLevel: 5 },
    { id: 'm-ch3', chapterId: 'skt-ch3-savage-frontier', grantsLevel: 5 },
    { id: 'm-ch4', chapterId: 'skt-ch4-chosen-path', grantsLevel: 5 },
    { id: 'm-ch5', chapterId: 'skt-ch5-grudd-haug', grantsLevel: 10 },
    { id: 'm-ch6', chapterId: 'skt-ch6-deadstone-cleft', grantsLevel: 10 },
    { id: 'm-ch7', chapterId: 'skt-ch7-svardborg', grantsLevel: 10 },
    { id: 'm-ch8', chapterId: 'skt-ch8-ironslag', grantsLevel: 10 },
    { id: 'm-ch9', chapterId: 'skt-ch9-lyn-armaal', grantsLevel: 10 },
    { id: 'm-ch10', chapterId: 'skt-ch10-maelstrom', grantsLevel: 11 },
    { id: 'm-ch11', chapterId: 'skt-ch11-tentacles', grantsLevel: 11 },
    { id: 'm-ch12', chapterId: 'skt-ch12-doom-of-the-desert', grantsLevel: 12 },
  ],

  questFlags: [
    { id: 'q-nightstone-cleared', title: 'Resolve the threat to Nightstone', introducedInChapter: 'skt-ch1-nightstone' },
    { id: 'q-town-defended', title: 'Defend a Savage Frontier town', introducedInChapter: 'skt-ch2-rumblings' },
    { id: 'q-met-harshnag', title: 'Find the frost giant Harshnag', introducedInChapter: 'skt-ch3-savage-frontier' },
    { id: 'q-consulted-oracle', title: 'Consult the Eye of the All-Father', introducedInChapter: 'skt-ch4-chosen-path' },
    { id: 'q-chosen-giant-lord', title: 'Choose a giant lord to pursue', introducedInChapter: 'skt-ch4-chosen-path' },
    { id: 'q-conch-recovered', title: 'Recover a conch of teleportation', introducedInChapter: 'skt-ch5-grudd-haug' },
    { id: 'q-allied-with-serissa', title: 'Ally with Princess Serissa at Maelstrom', introducedInChapter: 'skt-ch10-maelstrom' },
    { id: 'q-hekaton-freed', title: 'Free King Hekaton from the Kraken Society', introducedInChapter: 'skt-ch11-tentacles' },
    { id: 'q-iymrith-defeated', title: 'Defeat Iymrith', introducedInChapter: 'skt-ch12-doom-of-the-desert' },
  ],

  knowledgeFacts: [
    { id: 'k-ordning-shattered', fact: 'Annam the All-Father shattered the giants\' ordning; giant society is in upheaval.', visibility: 'player_known', revealedInChapter: 'skt-ch1-nightstone' },
    { id: 'k-nightstone-attacked', fact: 'Nightstone was just attacked (cloud giant rocks and goblin raiders) and is damaged/abandoned.', visibility: 'player_known', revealedInChapter: 'skt-ch1-nightstone' },
    { id: 'k-giants-attacking-towns', fact: 'Various giants are raiding settlements across the Savage Frontier.', visibility: 'player_known', revealedInChapter: 'skt-ch2-rumblings' },
    { id: 'k-harshnag-ally', fact: 'Harshnag is a good-aligned frost giant willing to help against the giant threat.', visibility: 'player_known', revealedInChapter: 'skt-ch3-savage-frontier' },
    { id: 'k-conch-artifacts', fact: 'Conches of teleportation, held by giant lords, can reach the storm giant court of Maelstrom.', visibility: 'player_known', revealedInChapter: 'skt-ch4-chosen-path' },
    { id: 'k-serissa-role', fact: 'Princess Serissa, Hekaton\'s youngest daughter, seeks to restore order and is a potential ally.', visibility: 'rumour', revealedInChapter: 'skt-ch10-maelstrom' },
    { id: 'k-hekaton-fate', fact: 'King Hekaton was abducted by the Kraken Society — not simply absent.', visibility: 'dm_secret', revealedInChapter: 'skt-ch10-maelstrom' },
    { id: 'k-kraken-society', fact: 'The Kraken Society is the sinister faction behind Hekaton\'s abduction.', visibility: 'dm_secret', revealedInChapter: 'skt-ch10-maelstrom' },
    { id: 'k-iymrith-true-role', fact: 'Iymrith, an ancient blue dragon, is the hidden mastermind manipulating events.', visibility: 'dm_secret', revealedInChapter: 'skt-ch12-doom-of-the-desert' },
  ],

  travelNodes: [
    { id: 'node-nightstone', name: 'Nightstone', region: 'Savage Frontier' },
    { id: 'node-triboar', name: 'Triboar', region: 'Savage Frontier', unlockedByChapter: 'skt-ch2-rumblings' },
    { id: 'node-goldenfields', name: 'Goldenfields', region: 'Sword Coast', unlockedByChapter: 'skt-ch2-rumblings' },
    { id: 'node-bryn-shander', name: 'Bryn Shander', region: 'Spine of the World', unlockedByChapter: 'skt-ch2-rumblings' },
    { id: 'node-eye', name: 'Eye of the All-Father', region: 'Spine of the World', unlockedByChapter: 'skt-ch4-chosen-path' },
    { id: 'node-maelstrom', name: 'Maelstrom', region: 'Sea of Moving Ice', unlockedByChapter: 'skt-ch10-maelstrom' },
  ],

  routes: [
    { fromNodeId: 'node-nightstone', toNodeId: 'node-triboar', distanceMiles: 40, danger: 'risky' },
    { fromNodeId: 'node-triboar', toNodeId: 'node-goldenfields', distanceMiles: 120, danger: 'risky' },
    { fromNodeId: 'node-triboar', toNodeId: 'node-bryn-shander', distanceMiles: 300, danger: 'dangerous' },
    { fromNodeId: 'node-bryn-shander', toNodeId: 'node-eye', distanceMiles: 120, danger: 'dangerous' },
  ],
};
